# Generated by Django 5.1 on 2024-09-14 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_alter_datasabertas_data'),
        ('paciente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_aberta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.datasabertas'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('documento', models.FileField(upload_to='documentos')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paciente.consulta')),
            ],
        ),
    ]
