# Generated by Django 5.1 on 2024-09-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_datasabertas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasabertas',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
